Dia 1 
Objetivo del analisis: Analizar los datos para ver la posibilidad de dónde abrir una escuela de buceo en los 3 lugares menos peligrosos.

In [78]:
pip install pandas

Requirement already satisfied: pandas in c:\users\mel\downloads\data\lab2\lab-dw-pandas\venv310\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\mel\downloads\data\lab2\lab-dw-pandas\venv310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mel\downloads\data\lab2\lab-dw-pandas\venv310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mel\downloads\data\lab2\lab-dw-pandas\venv310\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mel\downloads\data\lab2\lab-dw-pandas\venv310\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\mel\downloads\data\lab2\lab-dw-pandas\venv310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [79]:
#1. Download dataset and import it into Python.

import pandas as pd

#url = "https://raw.githubusercontent.com/roizherrerapilar-hub/Mini-project---Shark-Attacks/main/Shark_Attacks_Dataset.csv"

df = pd.read_csv('Shark_Attacks_Dataset.csv', sep=';')
pd.set_option('display.max_columns', None) #Con esta funcion vemos todas las columnas que tiene el archivo

C:\Users\MEL\AppData\Local\Temp\ipykernel_5260\2278032266.py:7: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Shark_Attacks_Dataset.csv', sep=';')

In [80]:
#2. Visualize the Dataframe 

df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,Unnamed: 153,Unnamed: 154,Unnamed: 155,Unnamed: 156,Unnamed: 157,Unnamed: 158,Unnamed: 159,Unnamed: 160,Unnamed: 161,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178,Unnamed: 179,Unnamed: 180,Unnamed: 181,Unnamed: 182,Unnamed: 183,Unnamed: 184,Unnamed: 185,Unnamed: 186,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196,Unnamed: 197,Unnamed: 198,Unnamed: 199,Unnamed: 200,Unnamed: 201,Unnamed: 202,Unnamed: 203,Unnamed: 204,Unnamed: 205,Unnamed: 206,Unnamed: 207,Unnamed: 208,Unnamed: 209,Unnamed: 210,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Unnamed: 222,Unnamed: 223,Unnamed: 224,Unnamed: 225,Unnamed: 226,Unnamed: 227,Unnamed: 228,Unnamed: 229,Unnamed: 230,Unnamed: 231,Unnamed: 232,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Unnamed: 242,Unnamed: 243,Unnamed: 244,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254
0,14/04,2026,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,Leg strpped off flesh later amputated in hospital,N,?,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,Bite wound to R ankle,N,?,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,Severe injuries to R arm,N,1730hrs,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,NaN,N,?,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,Graze injuries R leg and ankle,N,?,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
#3. Indicate the number of columns and rows. 
df.shape

(78395, 255)

In [82]:
#4. Delete the columns with null values (from column 16: source)
df = df.drop(columns=df.columns[15:]) 
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source
0,14/04,2026,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,Leg strpped off flesh later amputated in hospital,N,?,Unknown,The U.S. Sun: Simon De Marchi
1,3rd April,2026,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,Bite wound to R ankle,N,?,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...
2,26th March,2026,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,Severe injuries to R arm,N,1730hrs,Unknown,WIC News: Melissa Michaelson
3,25th March,2026,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,NaN,N,?,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF
4,22nd-23rd March,2026,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,Graze injuries R leg and ankle,N,?,Unknown,Melissa Michaelson: Instagram

In [83]:
#5. Indicate the names of the columns. 
df.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source'],
      dtype='object')

In [84]:
#6. Delete the rows with null values. 
df.dropna()
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source
0,14/04,2026,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,Leg strpped off flesh later amputated in hospital,N,?,Unknown,The U.S. Sun: Simon De Marchi
1,3rd April,2026,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,Bite wound to R ankle,N,?,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...
2,26th March,2026,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,Severe injuries to R arm,N,1730hrs,Unknown,WIC News: Melissa Michaelson
3,25th March,2026,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,NaN,N,?,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF
4,22nd-23rd March,2026,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,Graze injuries R leg and ankle,N,?,Unknown,Melissa Michaelson: Instagram

In [85]:
#7. Basic overview of the dataset. 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78395 entries, 0 to 78394
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       14177 non-null  object
 1   Year       14171 non-null  object
 2   Type       14139 non-null  object
 3   Country    14075 non-null  object
 4   State      13201 non-null  object
 5   Location   13041 non-null  object
 6   Activity   13009 non-null  object
 7   Name       13739 non-null  object
 8   Sex        13019 non-null  object
 9   Age        8187 non-null   object
 10  Injury     14103 non-null  object
 11  Fatal Y/N  13053 non-null  object
 12  Time       7121 non-null   object
 13  Species    7913 non-null   object
 14  Source     14135 non-null  object
dtypes: object(15)
memory usage: 9.0+ MB

Comentarios:
- Vemos que el data type de fecha es string y deberia ser data type object. 
- Los valores no nulos de las columnas: date, year, type, country, injury, source tienen valores similares. 
- Vemos que las columnas de age y time presentan en algunas filas un signo de interrogacion por falta de datos, por lo que mas adelante analizaremos que ocurre.

Clasificacion de las columnas: 
- Categorical: type, country, state, location, activity, name, sex, injury, fatal Y/N, species, source. 
- Numerical: date, year, age, time.

In [86]:
#8. Indicate the names of the columns.
print(df.columns.tolist())

['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ', 'Source']

In [87]:
#9. Analysis of categorical variables. 
df.describe()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source
count,14177,14171,14139,14075,13201,13041,13009,13739,13019,8187,14103,13053,7121,7913,14135
unique,6099,303,15,254,949,4632,1613,5802,12,179,4198,13,478,1747,5414
top,1957,2015,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,17,FATAL,N,Afternoon,White shark,"K. McMurray, TrackingSharks.com"
freq,22,282,10474,5160,2384,382,2302,1358,11364,348,1726,9886,430,388,262

Comentarios: 
- Vemos que la columna tiene presenta solo 14 valores unicos provocados siendo el valor total de 5413. Lo cual podemos deducir que hay algo raro que debemos de analizar posteriormente. 
- Vemos que la columna de country tiene 253 valores unicos, siendo el mas dominante, USA. Por lo tanto, se deduce que los ataques se concentran en USA. 
- Nos resulta sospechoso ver que el valor mas frecuente en la columna de date sea 1957, dado que no tiene formato de fecha mm/yy/dd. 
- En la columna de especies, nos llama la atencion que siendo 1746 especies unicas White Shark es la especie con mas ataques registrados en las costas de Florida.

# Día 2 - Data Cleaning Process
**Objetivo:** Limpiar el dataset de ataques de tiburón para identificar los 3 lugares menos peligrosos donde abrir una franquicia de buceo.

**Secciones:**
1. Manejo de valores nulos
2. Manejo de duplicados
3. Manipulación de cadenas de texto
4. Uso de regex
5. Formato de datos
6. Verificación final

In [88]:
#1. Valores nulos
#Hemos eliminado en la primera parte todas las columnas y filas con valores nulos.

In [89]:
# Count the number of null values in each column
df.isna().sum()

Date         64218
Year         64224
Type         64256
Country      64320
State        65194
Location     65354
Activity     65386
Name         64656
Sex          65376
Age          70208
Injury       64292
Fatal Y/N    65342
Time         71274
Species      70482
Source       64260
dtype: int64

In [90]:
#2. Valores duplicados
df = df.drop_duplicates()
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source
0,14/04,2026,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,Leg strpped off flesh later amputated in hospital,N,?,Unknown,The U.S. Sun: Simon De Marchi
1,3rd April,2026,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,Bite wound to R ankle,N,?,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...
2,26th March,2026,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,Severe injuries to R arm,N,1730hrs,Unknown,WIC News: Melissa Michaelson
3,25th March,2026,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,NaN,N,?,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF
4,22nd-23rd March,2026,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,Graze injuries R leg and ankle,N,?,Unknown,Melissa Michaelson: Instagram

In [114]:
df.shape 

#Vemos que el dataframe se ha reducido de (39196, 255) a (7087, 15)

(4013, 9)

In [115]:
#3. Manipulacion de strings
#Poner los nombres de las columnas en minuscula
df.columns = df.columns.str.lower()
df.head()

,country,state,location,activity,age,injury,species,age_range,fatal
1,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,16,Bite wound to R ankle,Bronze Whaler,<18,False
2,Bahamas,Andros Island,Fresh Creek,Swimming,22,Severe injuries to R arm,Unknown,18-25,False
4,Australia,NSW,Little Avalon Beach,Surfing,30,Graze injuries R leg and ankle,Unknown,26-35,False
5,USA,California,Big River Beach Mendocino County,Surfing,39,Injuries to both legs and feet,Great White Shark,36-50,False
8,Australia,Queensland,Lady Elliott Island,Snorkeling,50,Lacerations elbow and abdomen,Unknown,36-50,False

In [ ]:
#Columnas que consideramos importantes para nuestro proyecto: type, country, state, location, activity, age, injury, species. 
#4. Eliminacion de las columnas innecesarias:
df = df.drop(columns=['date', 'year', 'type', 'name', 'sex', 'fatal y/n', 'time', 'source'])
df.head()

In [94]:
#5. Clasificar las edades en rango. 
age_values = df['age'].tolist()
print(age_values)

['?', '16', '22', '?', '30+', '39', '?', '?', "50's", '55', '?', '13', '?', '?', '39', '11', '27', '12', '26', '?', '56', '?', '?', '?', '?', '55', '?', '24', '26', '25', '61', '40', '?', '?', '13', '14', '14', '50+', '54', '48', '57', '8', '8', '?', '63', '?', '9', '39', '19', '7', '85', '?', '69', '18', '66', '21', '40', '37', '16', '20', '?', '12', '9', '42', '26', '14', '66', '26', '45', '20', '30', '?', '30+', '37', '56', '40+', '29', '35', '58', '29', '24', '20', '55', '17', '12', '37', '36', '23', '40', '28', '?', '69', '48', '40', '60+', '?', '57', '24', '45', '61', '57', '27', '38', '16', '68', '33', '30', '16', '15', '23', '41', '14', '43', '26', 'Middle age', '18', '18', '21', '?', '49', '25', '15', '45', '46', '23', '19', '27', '20', '65', '64', '24', '16', '26', '?', '13', nan, '11', '46', '32', nan, '29', '10', '64', '62', '39', '22', '15', '16', '46', '21', '66', '52', '20', '44', '26', '21', '47', '32', '66', nan, nan, '66', '55', '30', '59', nan, '8', '50', '52', '45', '64', '52', nan, '34', '38', nan, nan, nan, '30s', '37', '44', '9', '19', '20/30', '35', nan, nan, '65', '22', '22', '26', '20s', '77', '60', '38', '49', '21', nan, '42', nan, '49', '47', '15', '15', '!2', nan, nan, '24', '73', '25', '42', '22', '18', '26', '15', '35', '20', '24', '46', '13', nan, nan, '22', '50s', '39', nan, '11', nan, '30', '50s', nan, '58', '67', '17', '30s', '60', '10', nan, '15', '14', '6', '32', '59', '60', '32', '41', '16', '8', '49', '34', '53', '30', '30', '26', '68', '15', '43', '60', nan, '10', '50', '29', nan, '40', nan, nan, '51', '19', '15', '40', '38', '17', '31', '39', '26', '58', '51', '14', nan, nan, nan, '17', '10', nan, nan, '13', '33', '16', nan, nan, nan, '40', '49', '41', '30s', '17', '60', '28', nan, nan, '40s', '68', nan, '17', '35', nan, nan, nan, nan, '62', 'teen', nan, nan, '20', nan, '62', nan, nan, '8', '22', '32', '56', '17', 'Teen', '12', nan, nan, '50s', '56', nan, '32', nan, '20', '21', nan, '42', '51', nan, '36', '56', '18', '37', '50', '20', 'M', nan, nan, '13', '42', '42', '40s', '9', '31', '42', '24', '14', '15', '15', nan, '11', '27', '57', nan, '26', '26', '34', '25', nan, '38', nan, '!6', '31', nan, '64', '!!', '41', '21', nan, '35', '15', nan, '12', '47', '15', '58', '34', nan, '32', '55', nan, '35', nan, '11', '38', nan, '9', '36', '51', '25', '8', '19', '31', '15', nan, '7', '38', '36', '25', '12', '14', '12', '71', '51', '10', nan, '26', '48', '59', '35', '57', '21', '14', '53', '64', '54', '25', '53', '57', nan, nan, '38', '38', '36', nan, '27', '10', '16', '7', '9', '75', '20', '16', '57', nan, nan, '17', '45 and 15', '46', '61', '58', nan, '73', '32', '57', '52', '54', '7', '26', '19', '19', '17', '68', nan, '40', '39', nan, '56', '20', '29', '42', '35', nan, '59', '13', '17', nan, nan, nan, '59', nan, '52', '31', '17', nan, '61', '30', '50s', nan, '48', '15', '25', '54', '46', '70', nan, nan, '12', nan, '23', '14', '50', nan, '35', '55', nan, '54', '22', '14', '28', '38', nan, '4', '63', '23', '11', nan, '12', '10', '14', '29', '15', '15', '36', '7', '16', nan, nan, '30', '60', nan, '12', nan, nan, '18', '12', '9', nan, '26', nan, '57', '16', nan, nan, '23', '38', 'Teen', nan, nan, nan, nan, '26', '60', nan, nan, '24', '59', '13', '26', '75', '7', '57', '12', '21', '30s', '45', '33', nan, '17', '37', nan, '70', '57', '22', '57', '9', '30', '38', nan, nan, '9', '30', '23', nan, nan, '44', '28 & 22', '32', nan, '35', '17', '20', '29', '51', nan, '45', nan, nan, '13', '22, 57, 31', '22', nan, '70', '60s', '40', '11', '26', '32', '9', '16', '51', '21', '20', '37', '49', nan, '18', nan, '49', '23', '18', nan, '45', nan, '16', "20's", '43', nan, '32', '18', '21', nan, '8', '50', '64', '19', nan, nan, '17', '43', '65', '10', '67', nan, nan, '53', '28', '34', '28', '12', nan, '18', '65', '25', '10', '58', '23', nan, '74', '25', '46', '32', '58', '11', nan, '46', nan, '41', '31', '25', nan, '50', nan, '50', '41', '17', '15', '9 & 60', '19', '35', '48', '24', '50', '36', '20s', '48', '17', '24', '31', '41', '20', '8', '42', '33', nan, nan, nan, '29', nan, '50', '25', nan, nan, nan, '55', '13', '17', '55', '30s', '32', nan, '43', '12', '46', '26', '39', '23', '60s', '40', nan, '14', '29', '14', '24', '56', nan, '61', '42', '16', 'a minor', '42', '14', '6', '13', '12', nan, '62', '58', '14', '17', '30', '14', '19', nan, '11', '57', nan, '11', '48', nan, nan, nan, '18', nan, '52', '15', '12', '32', '10', '10', '21', '34', nan, nan, nan, nan, '30', nan, nan, '60', nan, '32', '33', '29', '54', '34', '41', '37', nan, '56', '17', '12', '19', '25', '10', '69', '18', '38', '55', '34', '35', nan, '46', '45', '14', '18', '40s', '45', nan, '28', '20', nan, '54', '35', '24', '25', '62', '26', '49', nan, '25', '14', '24', '25', '22', '20s', '7', '31', nan, nan, '17', '60', '15', nan, nan, '54', '40', '31', nan, nan, '33', nan, nan, '13', '28', '25', nan, nan, '18', nan, '35', nan, nan, '42', nan, nan, '17', '37', '3', '11', nan, '69', nan, '13', '20', '34', nan, '15', '10', '12', nan, nan, '37', nan, nan, '40', '8', '40', '50', nan, nan, nan, '46', '32', '13', nan, nan, '16', nan, '14', '34', '82', nan, nan, '48', nan, '19', '30', nan, '32', '20', nan, '73', '41', '29', '33', '18', nan, '14', '33', '28', '20s', nan, '40', nan, nan, '17', '28', '17', nan, '68', '35', '10', '21', '16', '51', '39', '17', '58', '30', nan, '25', '58', nan, nan, nan, nan, '26', '26', '22', nan, nan, nan, '37', '13', '21', 'Teen', '55', '57', nan, '48', '35', '47', '20', '16', nan, '55', '61', '40s', '19', '20', '65', '73', '40?', '58', '41', '42', '36', '36', nan, '66', nan, '25', '29', '?', '21', '32', '17', '16', '36', '43', '43', nan, nan, nan, '60s', '51', '50', '12', nan, '9', '22', nan, '25', '37', '20', '49', '15', '21', '22', '40', '72', nan, '43', '18', '29', '36', nan, '31', nan, '9', '11', '61', nan, nan, '10', nan, '59', nan, '42', '34', '35', '11', '59', '43', '42', nan, nan, '19', '6', '19', '27', '64', '60', '23', nan, nan, '29', '52', '13', '57', '22', '11', '48', '23', '59', '39', '33', '24', '15', nan, '12', '22', '26', '26', '69', '60', '34', nan, '46', '22', 'Teen', '41', '9', nan, '19', '45', '12', nan, '41', '21', '31', nan, '65', nan, '45', '40', '41', nan, nan, '15', nan, nan, '48', nan, '11', '31', nan, '38', '71', '43', '32', '58', nan, '26', '22', '55', nan, nan, '28', '20', '9', '54', '28', '19', '50', '10', '42', '21', '21', '35', '32', '44', nan, '9', '25', nan, '18', '22', '13', '14', '22', '7', nan, '14', '27', '12', '16', nan, nan, '20', '42', '50', '29', '62', nan, '37', nan, '54', '21', nan, '38', '15', '10', '22', '10', '57', '52', '47', '40', '25', '35', '46', '31', '40', '45', '34', '38', '39', nan, '23', '32', '52', '32', '68', nan, '12', '18', '19', nan, '23', '43', '19', '47', '6', '37', '9', '36', '10', '16', '12', nan, '13', '11', '17', '47', '14', '19', '19', '13', '18', '30', '50', nan, nan, '29', '65', '63', '26', '71', '48', '13', nan, '70', '43', '23', '36', '52', '58', '9', nan, '36', '18 months', nan, '22', '41', '35', nan, '57', '20', nan, '24', nan, nan, nan, '17', '38', '34', '15', '12', nan, '17', nan, nan, '50', '40s', nan, '17', nan, '13', '39', nan, nan, '44', '53', nan, '18', '34', '20', nan, nan, nan, '13', '7', nan, nan, '29', '40', '15', nan, nan, '28', '23', nan, '36', nan, '50', '43', '20s', '52', '16', '13', '17', nan, '33', '30s', '29', nan, nan, nan, '31', nan, '26', nan, '10', '7', '10', '45', '50s', '8', '20', nan, 'Teen', '51', '8', nan, '61', '39', '63', nan, '14', nan, nan, '19', '48', '42', nan, '15', nan, '43', '16', '39', '43', '14', '22', nan, '37', '29', nan, '10', '38', '35', '44', '12', nan, '40', nan, '23', nan, '42', '25', nan, nan, '13', '14', '63', '38', '66', nan, '9', '42', '42', '10', nan, nan, '21', '21', '21', '28', nan, '28', nan, '24', '31', nan, nan, '37', '19', '35', '29', '30', '26', '57', '19', '58', '35', '25', nan, '77', '16', nan, '46', '60', '24', nan, '41', '45', '25', '6', '74', '55', '45', '12', '50', '27', '7', '45', nan, '21', '13', nan, '43', '25', '17', '3', nan, '9', nan, nan, '47', '50', '11', nan, '16', nan, '20', '19', '10', nan, '17', '56', '32', '40', nan, '18', '64', '50', '18', '50', 'teen', '15', '33', '63', '48', '29', nan, '20', nan, nan, '14', '28', '15', nan, nan, '10', '58', nan, '32', '11', '41', '30', '29', '42', '36', '16', nan, '34', '51', '9', nan, '21', '40', '53', '50', '24', '58', '47', '34', nan, '50', '30', nan, '68', '28', '28 & 26', '39', '46', nan, nan, '16', '48', '18', nan, nan, '62', '43', nan, '26', nan, '23', '29', '20', '32', '60', '31', '25', '61', '20', '32', '14', '30', '43', '25', '51', '39', '35', '24', '55', nan, '38', '42', '11', '21', '22', '52', '29', '19', '25', nan, '30s', '37', '32', '8', nan, '56', '53', '34', '18', '31', nan, '56', '39', nan, '17', '48', '44', '50', '12', '22', '24', '23', '24', '43', nan, '42', '52', '29', '60', '6', '26', '16', nan, '12', '62', '16', '6', '23', '18', nan, nan, '16', '42', '57', '30', '12', '25', '33', '46', '22', nan, '20', '30', '47', '15', '28', '20', '27', '28', nan, '33', '21', nan, '20', '61', '15', '17', nan, '34', '31', '19', '42', nan, nan, nan, nan, '29', nan, '26', nan, '24', '44', '25', '53', '28', '34', nan, nan, '23', '27', nan, '35', '51', nan, '14', nan, nan, '63', '18', '10', nan, nan, '35', '42', '27', '26', nan, '32', '41', '50', nan, nan, '64', '51', nan, '29', '27', '48', '43', '21', '5', nan, '38', '17', '25', '37', '30', nan, '21', '19', '19', '48', '39', nan, '21', '10', '49', '16', '20s', '12', '25', '32', '27', '30', '7', '54', '36', '14', '43', nan, '29', '6', nan, nan, '54', '12', '14', '16', '17', '28', '21', '22', '10', nan, '20', '35', '15', '31', nan, '28', '24', '28', '19', nan, '22', '33', nan, nan, '28', '86', '15', '37', nan, '43', '37', '32', '17', '49', '41', nan, '27', nan, nan, '48', '46', '30', '24', nan, nan, '36', '21', '32', '49', nan, '58', nan, '37', '38', '25', '55', '7', '16', '37', nan, '16', nan, '46', '70', nan, '54', '46', '70', '48', '47', nan, '33', '21', nan, nan, '20', nan, nan, nan, '30', '14', '19', nan, '22', nan, nan, 'Teen', '29', '18', '29', '15', '27', '24', nan, '24', '24', '34', '43', '10', '31', '45', nan, '16', '47', '25', '35', nan, nan, '37', '16', '20', '10', '13', '55', '9', nan, nan, '21', '20', '19', '48', '20', '6', '13', '17', '18', '40', '20', '49', '58', '60', nan, '59', '10', '29', '68', '35', '24', '34', nan, nan, '19', '60', '46', nan, '18', nan, '31', '38', '14', '29', nan, '54', nan, '37', '9', nan, nan, nan, '32', nan, '20', '55', '27', nan, '18', '22', nan, '24', '39', nan, '58', '49', '10', '31', '22', '27', '18', '25', '21', '27', nan, '17', nan, '54', '10', '23', '23', nan, '39', nan, nan, nan, '34', '60', '15', nan, nan, nan, '25', '22', nan, '26', nan, '56', '14', '14', '41', nan, '14', '11', '26', '19', '57', nan, nan, '37', '12', '43', '52', '26', '14', nan, nan, nan, '50', '46', nan, '31', '49', '55', '27', '48', nan, nan, '20', '23', '52', '31', '49', '40', '24', nan, '15', '59', '16', '17', nan, nan, '17', nan, '61', '21', '19', '40', nan, '15', nan, nan, '33', '31', nan, '41', nan, '49', '17', '15', nan, '19', '25', '17', nan, nan, nan, '24', '13', '31', nan, '22', '49', nan, nan, nan, '10', '29', '51', nan, nan, '15', nan, nan, nan, nan, nan, nan, '45', '39', '34', '24', '50', '15', '11', '43', '44', '40', '43', '32', '40', nan, '51', '43', '15', '52', nan, '29', '27', '52', '19', '26', '20', '20', '47', '7', '38', '13', nan, '31', nan, nan, '33', nan, '17', '44', '9', '8', '15', '16', nan, '52', '24', '14', '17', '16', '53', '42', '46', nan, '29', '37', nan, '40', '35', '14', '40', nan, '15', '14', '9', nan, '49', '21', '28', '37', '40', '6', '24', '24', '18', '24', '32', '21', '66', '14', nan, nan, '32', '19', '30', nan, '15', nan, '16', '18', '39', '52', nan, '13', '14', '8', '27', '49', '26', '25', '14', nan, nan, '42', '20', nan, nan, '20', nan, '26', '24', '53', '31', 'teen', '34', '52', nan, '28', '32', nan, '14', '21', '42', '37', nan, '32', '52', '31', '22', '16', nan, nan, '23', '48', nan, '18 or 20', nan, nan, '23', nan, '56', 'Teen', '14', '58', '36', '15', '12', '58', '15', '24', '54', '27', nan, nan, '52', '16', '7', '20', '15', '19', '30', '9', '19', '51', '20', nan, nan, '36', '15', '14', '48', '43', '30', '48', '18', '17', nan, nan, nan, '20', nan, '9', nan, nan, nan, '40', '38', '38', '19', '21', nan, '45', '63', '68', nan, '20', '13', '12', '24', nan, '26', '7', '27', '9', nan, '11', '42', nan, '59', '29', '16', '36', '26', nan, '30', nan, '41', '20', '24', nan, '54', '24', nan, '25', '10', '43', '25', '15', nan, '29', nan, '22', '15', '20', nan, '18', '26', nan, '36', '19', nan, '16', '55', '52', '44', '20', '33', '12 or 13', '37', '23', nan, '27', '17', '34', nan, '34', nan, '24', '59', nan, nan, '41', nan, '15', '19', '14', nan, nan, '49', '7', '21', nan, '40', '11', '14', '13', '28', '35', '9', nan, '25', '22', '27', '43', '24', '7', '40', '26', nan, '31', '15', '33', '30s', nan, '20s', '46', nan, '54', '13', '35', '15', '15', '35', '11', nan, '28', '17', '21', '15', '15', '45', '18', nan, nan, '15', '24', '57', '46 & 34', '34', '28, 23 & 30', nan, '52', nan, '21', '21', '49', '30', '29', nan, '44', nan, 'teen', '23', nan, '18', '26', nan, '30s', '17', nan, '32', '18', '25', '26', '15', '55', '20', '36', '20', '15', '22', '57', '48', '35', '52', '28', '26', '44', nan, '68', '18', '15', '18', '40', '62', '21', '23', '37', '17', '8', '12', nan, '16', '14', nan, '13', '61', '25', nan, '24', nan, '22', '14', '19', '16', '14', '7', nan, '49', '20', '38', '11', '17', '22', '6', '33', nan, '32', nan, nan, nan, 'Teens', '47', '25', nan, '20', '40', '70', '52', '37', nan, nan, '32', nan, nan, '26', '45', '51', nan, nan, '18', nan, nan, nan, '12', '19', nan, nan, '39', '11', '18', '38', '20', '16', '77', '38', '30s', nan, '40', nan, '52', '59', nan, '34', '34', '15', '16', '40', nan, '26', nan, nan, '17', '38', '24', nan, '50', '47', '30', nan, '20', nan, '28', '13', '19', '11', nan, '51', '30', 'Teen', '7', '45', nan, nan, '17', '8', '21', '16', '17', '44', '9', '9', '9', '24', '63', '28', '22', nan, nan, nan, nan, '57', '16', '22', '26', '20', '22', nan, '20', '61', nan, nan, '51', '47', '29', '15', nan, '31', nan, '22', '46', '21', nan, nan, '40', nan, nan, '22', nan, nan, nan, nan, '28', '13', '45', '36', nan, nan, '21', '35', '35', '24', nan, nan, nan, nan, '18', '22', '13', '46', '56', '19', nan, nan, '18', '30', '50', '41', '40', '16', '21', '19', '17', '30', '36 & 26', '8 or 10', '18', '15', '19', nan, nan, '50', '31', '16', '37', '18', '15', '58', '10', '21', '39', nan, nan, nan, '17', '15', nan, '12', '60', '51', '33', '15', '22', '18', '22', '20', '34', '9', nan, nan, '16', '17', '7', '36', '17', '30', '23', '18', '11', '12', '20', '28', nan, '50', nan, '44', '37', '54', '24', '84', '14', nan, nan, '18', '25', '26', '11', '23', '19', nan, '48', '34', '41', '21', '16', '52', '60', '36', '21', '14', '35', '18', '47', '32', '55', '\xa0 ', ' ', '24', '35', '19', nan, '47', '20', '36', '16', '29', '27', '15', '15', '30', '14', '13', '15', '19', '41', '22', '9', '30', '11', nan, nan, nan, nan, '28', '50', '10', '50', '24', '16', '55', '35', nan, '14', '31', '40', '20', '23', '52', '34', '28', '45', '43', '41', '29', '17', '11', '16', '20', '39', '31', '44', nan, '30 or 36', '15', '35', '20', '32', '16', nan, '26', '35', '36', '49', nan, nan, nan, '20', '26', '31', '21', '14', '42', '6½', '16', nan, '44', '13', nan, '28', '23', '20', '10', '44', '29', '69', '18', '18', '17', '27', '32', '17', '17', '20', '19', '19', '43', '21 & ?', nan, '36', nan, nan, nan, nan, nan, '48', '18', '42', '8', nan, '35', '14', '52', '75', '29', '16', '11', nan, '24', nan, '26', '33 or 37', '45', nan, '14', '16', '12', 'mid-30s', '38', '21', '12', '22', '19', '22', nan, '16', '46', nan, '26', '12', '40', nan, nan, '12', '20', nan, nan, nan, '40', '35', '55', nan, nan, nan, '23', '47', nan, '30', '38', nan, '28', '47', '73', '27', '52', '49', '27', '31', '23', '56', '69', '17', '23', '11', '24', nan, '17', '25', '12', '31', nan, '49', '26', '25', '8', '48', '28', '40', '27', nan, '47', '69', nan, nan, '53', '27', '44', nan, '23 & 20', nan, '5', '45', '16', '14', '15', '18', nan, '69', '13', '41', '5', '12', '20', '55', '13', '19', nan, nan, nan, '52', nan, '17', '55', '44', '13', nan, nan, nan, '9', nan, '34', nan, nan, '26', '14', '37', '35', nan, nan, nan, '27', nan, '39', '27', nan, nan, '12', '26', nan, '35', nan, '15', '13', '12', '18', nan, '39', '35', '19', '51', nan, '35', '39', '12', '12', '45', '13', nan, '16', '22', nan, '37', '61', '10', '13', '7', '39', '28', nan, '23', '17', '10', '62', '35', '42', '43', '43', '14', nan, '30', '29', '20', '21', '41', '5', '22', '21', '41', '52', '14', nan, nan, '29', nan, '28', '18', '29', nan, '35', '25', '47', nan, nan, '37', nan, '30', nan, '19', '21', '18', '14', '21', '9', '14', '13', '32', '52', '22', '17', '30', nan, '17', nan, '28', '6', '18', nan, '28', '25', '26', nan, '16', nan, '28', '11', nan, '19', '24', nan, '13', '47', '16', '10', '26', '20', '18', nan, '17', '15', '16', '40', '14', '24', '22', '35', '50', '16', nan, nan, '40', '33', '32', nan, '31', nan, nan, '21', nan, '23', '28', nan, nan, '39', nan, '29', '8', '42', '32', '21', '51', '19', '23', '12', nan, '14', '20', '12', '17', '20', '18', '22', '29', '28', '33', '12', '17', '16', '17', nan, '10', nan, '17', '19', '19', '25', nan, '50', '55', nan, nan, '47', '18', nan, '33', '35', '34', '12', '54', nan, '22', '21', ' 30', nan, nan, '49', '27', '41', nan, nan, '18', nan, nan, nan, '45', '26', nan, nan, nan, '22', '21', '31', nan, '14', '23', '19', '5', '28', '28', '29', '19', '36', '21', '8', '52', nan, '46', '9', nan, '18', '63', '24', '24', nan, nan, '17', '45', '22', '33', '27', nan, '11', '16', nan, '47', '7', '24', '32', nan, nan, '14', nan, '7', '33', '13', '53', nan, nan, '25', nan, nan, nan, '22', nan, nan, nan, '13', '17', '15', '39', '14', '17', '25', '19', '19', nan, '25', '29', '32', '9', '19', '44', nan, '16', '18', '16', '23', '19', nan, '18', '20', '15', '20', '14', '12', nan, nan, nan, nan, '18', '18', '12', '7', '47', '18', '14', '34', '32', nan, '31', nan, '13', nan, '45', '10', '38', '45', '29', '44', '15', '69', nan, '44', '12', '20', nan, '47', nan, '35', nan, '22', nan, '14', '17', '33', nan, nan, nan, '26', nan, nan, nan, nan, nan, '44', '42', nan, nan, '34', nan, nan, nan, '9', '16', '30', '43', '7      &    31', '12', nan, '15', nan, '24', '22', '31', nan, '15', '30', '24', ' 28', '35', '36', '26', '22', '25', '?', '20?', '71', nan, '19', nan, '33', '25', nan, '23', nan, '15', nan, nan, nan, '44', nan, '23', '33', nan, nan, nan, '30', '27', nan, nan, '26', '26', '34', nan, '21', '36', '15', '17', '19', '16', '69', '51', '13', nan, nan, '19', nan, '39', nan, nan, '28', '12', nan, '16', '61', '42', '22', '31', '34', '42', "60's", nan, nan, '32', nan, '25', nan, '35', '55', nan, nan, nan, '69', '15', '21', '32 & 30', '29', nan, nan, '30', nan, '10', '30', '31', '19', '24', '46', '30', '40', '17', '18', '40', '28', nan, nan, '28', nan, '20', '18', nan, nan, '34', '17', nan, '22', '26', nan, nan, '42', nan, nan, nan, '16', '21', nan, nan, '45', nan, nan, nan, '35', '36', '17', '41', nan, '21', nan, nan, '19', nan, '19', '19', '36', nan, nan, nan, '33', '25', '41', nan, nan, nan, '14', '21', '32', '32', '19', '36', '23', '10', nan, '40', '39', '42', '70', '22', '30', '32', '13', '22', nan, '18', '31', '65', '23', nan, nan, nan, '22', nan, '18', '38', '20', '35', nan, '22', nan, '26', nan, '24', '50', '18', '26', nan, '25', '43', '19', '26', '49', '44', '30', '22', nan, '18', '51', '53', '17', '21', '38', nan, '30s', '30s', '22', '23', '31', '37', nan, '29', nan, '30', nan, nan, '33', nan, '17', nan, '17', '27', '32', '29', nan, '10', '31', '17', nan, '12', '49', nan, '29', '51', nan, '38', '31', '46', '30', '21', '21', '17', '31', '41', '35', '34', nan, '16', '9', nan, '45', nan, '16', '28', nan, '19', nan, nan, nan, nan, '27', nan, nan, '26', '47', '24', '24', '10', '19', nan, '17', nan, nan, nan, '17', '

In [95]:
try:
    df = pd.read_csv('Shark_Attacks_Dataset.csv', sep=';', low_memory=False)
    print("✅ Cargado: Shark_Attacks_Dataset.csv")
except FileNotFoundError:
    df = pd.read_csv('Dataset_CSV.csv', sep=';', low_memory=False)
    print("✅ Cargado: Dataset_CSV.csv")

✅ Cargado: Shark_Attacks_Dataset.csv

In [96]:
df = df.drop(columns=df.columns[15:])
df.columns = df.columns.str.lower()
print(df.columns.tolist())

['date', 'year', 'type', 'country', 'state', 'location', 'activity', 'name', 'sex', 'age', 'injury', 'fatal y/n', 'time', 'species ', 'source']

In [97]:
df = df.drop(columns=df.columns[15:])
df.columns = df.columns.str.lower().str.strip()

In [98]:
# Eliminar solo las columnas que existan
cols_to_drop = ['date', 'year', 'type', 'name', 'sex', 'fatal y/n', 'time', 'source']
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])
df = df.drop_duplicates().reset_index(drop=True)

In [99]:
print(f'Shape de partida: {df.shape}')
print(f'Columnas: {df.columns.tolist()}')
df.head()

Shape de partida: (7053, 7)
Columnas: ['country', 'state', 'location', 'activity', 'age', 'injury', 'species']

,country,state,location,activity,age,injury,species
0,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,?,Leg strpped off flesh later amputated in hospital,Unknown
1,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,16,Bite wound to R ankle,Bronze Whaler
2,Bahamas,Andros Island,Fresh Creek,Swimming,22,Severe injuries to R arm,Unknown
3,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,?,NaN,Great White Shark 3.5m (11.5ft)
4,Australia,NSW,Little Avalon Beach,Surfing,30+,Graze injuries R leg and ankle,Unknown

In [100]:
# Función regex: extrae el primer número entero que encuentre
# \d+ = uno o más numeros consecutivos

def extraer_edad(valor):
    match = re.search(r'\d+', str(valor))
    return float(match.group()) if match else None

In [101]:
df['age'] = df['age'].apply(extraer_edad)

In [102]:
# Eliminar filas donde no se pudo extraer ningún número
df = df.dropna(subset=['age'])

# Filtrar edades imposibles
df = df[(df['age'] >= 1) & (df['age'] <= 100)]

In [103]:
print(f'Shape tras limpiar age: {df.shape}')
print(f'Rango de edades: {int(df["age"].min())} - {int(df["age"].max())} años')

Shape tras limpiar age: (4028, 7)
Rango de edades: 1 - 87 años

In [104]:
# Convertir age a entero (ya sin nulos ni valores imposibles)
df['age'] = df['age'].astype(int)

In [105]:
# Crear rangos de edad con pd.cut()
bins   = [0, 17, 25, 35, 50, 65, 100]
labels = ['<18', '18-25', '26-35', '36-50', '51-65', '65+']

In [117]:
df['age_range'] = pd.cut(df['age'], bins=bins, labels=labels, right=True)

In [107]:
print('Distribución por rango de edad:')
print(df['age_range'].value_counts().sort_index())

Distribución por rango de edad:
age_range
<18      1072
18-25    1077
26-35     804
36-50     689
51-65     312
65+        74
Name: count, dtype: int64

In [108]:
# Rellenar nulos restantes en columnas no críticas con 'Unknown'
for col in ['state', 'location', 'activity', 'species']:
    df[col] = df[col].fillna('Unknown')

In [109]:
print('Nulos restantes:')
print(df.isna().sum())

Nulos restantes:
country      9
state        0
location     0
activity     0
age          0
injury       6
species      0
age_range    0
dtype: int64

#comentario
-Solo quedan 9 nulos en country y 6 en injury. Los eliminamos porque son columnas críticas para nuestro análisis:

In [110]:
#Dado que necesitamos saber el dato de en que countries hubo ataques eliminamos los datos de los que no tenemos esa informacion
# Sin país no podemos ubicar el ataque, sin injury no sabemos si fue fatal
df = df.dropna(subset=['country', 'injury'])
print(f'Shape final: {df.shape}')

Shape final: (4013, 8)

In [111]:
#Para conseguir un ranking necesitamos una tasa de fatalidad y mortalidad con la cual poder descartar paises de forma rotunda y saber con cuales quedarnos
# Crear columna booleana 'fatal'
# True  → el texto de injury contiene la palabra 'fatal'
# False → cualquier otro caso

df['fatal'] = df['injury'].str.contains('fatal', case=False, na=False)

print('Distribución fatal vs no fatal:')
print(df['fatal'].value_counts())
print(f'\n% ataques fatales: {df["fatal"].mean()*100:.1f}%')

Distribución fatal vs no fatal:
fatal
False    3331
True      682
Name: count, dtype: int64

% ataques fatales: 17.0%

#Comentario 
-De 4017 ataques registrados, 683 fueron fatales — un 17%.

In [118]:
#VERIFICAMOS
print('=== SHAPE FINAL ===')
print(df.shape)

print('\n=== TIPOS DE DATOS ===')
print(df.dtypes)

print('\n=== NULOS RESTANTES ===')
print(df.isna().sum())

print('\n=== DUPLICADOS ===')
print(f'Duplicados: {df.duplicated().sum()}')

=== SHAPE FINAL ===
(4013, 9)

=== TIPOS DE DATOS ===
country        object
state          object
location       object
activity       object
age             int64
injury         object
species        object
age_range    category
fatal            bool
dtype: object

=== NULOS RESTANTES ===
country      0
state        0
location     0
activity     0
age          0
injury       0
species      0
age_range    0
fatal        0
dtype: int64

=== DUPLICADOS ===
Duplicados: 0

In [119]:
df.head(5)

,country,state,location,activity,age,injury,species,age_range,fatal
1,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,16,Bite wound to R ankle,Bronze Whaler,<18,False
2,Bahamas,Andros Island,Fresh Creek,Swimming,22,Severe injuries to R arm,Unknown,18-25,False
4,Australia,NSW,Little Avalon Beach,Surfing,30,Graze injuries R leg and ankle,Unknown,26-35,False
5,USA,California,Big River Beach Mendocino County,Surfing,39,Injuries to both legs and feet,Great White Shark,36-50,False
8,Australia,Queensland,Lady Elliott Island,Snorkeling,50,Lacerations elbow and abdomen,Unknown,36-50,False

#Traas la ejecuccion del documento podemos ver lo siguiente:
- falta de coherencia de formato
- caractares inusuales en las explicaciones
-En el apartado de state observamos siglas en los nombres sin poder identificar bien el lugar.

In [123]:
df['state'] = df['state'].str.replace('NSW', 'New South Wales', case=False)
df['state'] = df['state'].str.replace('Between New Ireland & New Britain', 'New Ireland / Britain', case=False)
df['state'] = df['state'].str.title()

df['injury'] = df['injury'].astype(str).str.strip()
df['injury'] = df['injury'].str.replace(r'\bR\b', 'right', case=False, regex=True)
df['injury'] = df['injury'].str.replace(r'\bL\b', 'left', case=False, regex=True)
df['injury'] = df['injury'].str.lower().str.capitalize()

print(df['injury'].unique()[:10])

['Bite wound to right ankle' 'Severe injuries to right arm'
 'Graze injuries right leg and ankle' 'Injuries to both legs and feet'
 'Lacerations elbow and abdomen' 'Deep wounds arms and legs'
 'Right thigh and lower leg stripped of flesh' 'Minor cuts and abrasions'
 'None reported damage to board' 'Serious leg injuries']

In [125]:
df.head()

,country,state,location,activity,age,injury,species,age_range,fatal
1,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,16,Bite wound to right ankle,Bronze Whaler,<18,False
2,Bahamas,Andros Island,Fresh Creek,Swimming,22,Severe injuries to right arm,Unknown,18-25,False
4,Australia,New South Wales,Little Avalon Beach,Surfing,30,Graze injuries right leg and ankle,Unknown,26-35,False
5,USA,California,Big River Beach Mendocino County,Surfing,39,Injuries to both legs and feet,Great White Shark,36-50,False
8,Australia,Queensland,Lady Elliott Island,Snorkeling,50,Lacerations elbow and abdomen,Unknown,36-50,False